---
version: "2"
checks:
  method-complexity:
    config:
      threshold: 20
  similar-code:
    config:
      threshold: 50
  identical-code:
    config:
      threshold: 50
plugins:
  csslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
exclude_patterns:
  - test/
  - src/common/components/img/
  - src/common/store/coreSet/
  # The following are by-and-large not our own code, so it's not worth analyzing them:
  - src/common/components/Sprite.js
  - styles/lib.css
