---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
    exclude_paths:
      - "src/common/store/cards.js"  # We don't care about duplicates in store/cards.js.
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.jsx"
  - "**.md"
exclude_paths:
  - test/
  - src/common/components/img/
  # The following are by-and-large not our own code, so it's not worth analyzing them:
  - src/common/components/Sprite.js
  - src/common/components/hexgrid/
  - src/common/components/react-textfit/
  - styles/lib.css
