---
version: "2"
plugins:
  csslint:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
exclude_patterns:
  - test/
  - src/common/components/img/
  - src/common/store/coreSet/
  # The following are by-and-large not our own code, so it's not worth analyzing them:
  - src/common/components/Sprite.js
  - styles/lib.css
