version: 2
jobs:
  test:
    working_directory: ~/wordbots/wordbots-core
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/node:8.11-browsers
        command: /sbin/init
    steps:
      # Machine Setup
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

      # Dependencies
      - restore_cache:
          keys:
          # This branch if available
          - v1-dep-{{ .Branch }}-
          # Default branch if not
          - v1-dep-master-
      - run: yarn install --no-optional
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
          - ./node_modules
      # Print useful information for debugging CI issues.
      - run: |
          node --version
          npm --version
          yarn --version
          env
      - run: yarn list

      # Test
      - run: node_modules/eslint/bin/eslint.js .
      - run: yarn test --coverage
      - run: NODE_ENV=test yarn start
      - run: cp -R coverage $CIRCLE_ARTIFACTS
      - run: |
          yarn global add codeclimate-test-reporter
          codeclimate-test-reporter < coverage/lcov.info

      # Teardown
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
